@startuml
autonumber

actor "Admin" as USER

participant "FrontEnd" as FE
participant "BackEnd" as BE

activate USER

  
    USER -> FE : chooses the filter to be applied
    activate FE
    
    alt search by id
    
    FE -> BE : GET/staff/id 
    activate BE
    
    alt the search is successfull
    BE --> FE : staff with key staff information (name, email,specialization) and staffID
    
    FE --> USER: shows staff with key staff information (name, email,specialization) and staffID
    else error
    
    BE --> FE: error message
    deactivate BE
    
    FE--> USER: shows error message

end 
    else admin chooses to search by staffName filter
    
    FE -> BE : GET/staff?staffName={staffName}
        activate BE
        
        alt the search is successfull
            BE --> FE : list of staffs associated to the specified staffSpecialization \n and key staff information (name, email,specialization) and staffID
        
            FE --> USER : shows list of staffs associated to the specified staffSpecialization \n and key staff information (name, email,specialization) and staffID
        else error
        
        BE --> FE: error message
        deactivate BE
        
        FE--> USER: shows error message
    
    end
    
    else admin chooses to search by userEmail filter
       
        FE -> BE : GET/staff?userEmail={userEmail}
            activate BE
            
            alt the search is successfull
            BE --> FE : staff with key staff information (name, email,specialization) and staffID
            
            FE --> USER: shows staff with key staff information (name, email,specialization) and staffID
            else error
            
            BE --> FE: error message
            deactivate BE
            
            FE--> USER: shows error message
    end
    
    else admin chooses to search by staffSpecialization filter
        
        FE -> BE : GET/staff?staffSpecialization={staffSpecialization}
            activate BE
            
            alt the search is successfull
            BE --> FE : list of staffs associated to the specified staffSpecialization \n and key staff information (name, email,specialization) and staffID
            
            FE --> USER: shows list of staffs associated to the specified staffSpecialization \n and key staff information (name, email,specialization) and staffID
            else error
            
            BE --> FE: error message
            deactivate BE
            
            FE--> USER: shows error message
            deactivate FE
    
    end
    end 
deactivate USER

@enduml