@startuml
autonumber

actor "Patient" as USER

participant "FrontEnd" as FE
participant "BackEnd" as BE
participant "Firebase IAM API" as FIREBASE
participant "SMTP API" as EMAIL

activate USER

    USER -> FE : wants to register for healthcare application
    activate FE
    
        FE --> USER : provides IAM options
    deactivate FE

    USER -> FE : selects one and accepts terms
   
        activate FE
        
            alt User Already Exists
               
            FE -> BE : create user in IAM
            activate BE
            
                BE --> FE : error: user already exists
            deactivate BE 
            FE --> USER : informs error with suggestion
            
            else User Created Successfully
            
            FE -> BE : create user in IAM
            activate BE
            
                BE -> FIREBASE : create user
                activate FIREBASE 
                
                    FIREBASE --> BE : success: created user
                deactivate FIREBASE
                
                BE -> EMAIL : send confirmation email
                activate EMAIL
                
                    EMAIL --> BE : email sent
                deactivate EMAIL
            
                BE --> FE : success: created user (returns user ID)
            deactivate BE
               
            FE --> USER : shows created user
        deactivate FE
    end
            
deactivate USER

@enduml