@startuml

title Class Diagram

class User {
    - UserEmail
    - UserPassword
    - Username
    - UserRole
    - IsActive
    + User(UserEmail userEmail, Username username, UserRole userRole, Password password)
    + ChangeUsername(Username username)
    + ChangeUserRole(UserRole userRole)
    + ChangePassword(Password password)
    + ActivateUser()
    + DeactivateUser()  
}

class UserDTO {
    - UserEmail
    - UserPassword
    - UserName
    - IsActive
    + UserDTO(string userEmail, string userName, string password)
    + ChangeUserName(string userName)
    + ChangePassword(string password)
    + ActivateUser()
    + DeactivateUser()
}

class UsersController {
    + GetAll()
    + GetGetById(String id)
    + Create(UserDto dto)
    + Update(String id, UserDto dto)
    + SoftDelete(String id)
    + HardDelete(String id)
}

class UserId {
    + UserId(string value)
}

class Username {
    + Username(string username)
}

class UserEmail {
    + UserEmail(string email)
}

class UserRole {
    + UserRole(string role)
}

class Password {
    + Password(string password)
}

class UserService {
    + GetAllAsync()
    + GetByIdAsync(UserId id)
    + AddAsync(UserDto dto)
    + UpdateAsync(UserDto dto)
    + InactivateAsync(UserId id)
    + DeleteAsync(UserId id)
}

interface IUserRepository {
}

interface UserRepository {
}

class BaseRepository {
    ====
    Classe do projeto base
    ====
}

class UserMapper {
    + ToDomain(UserDto dto, UserId userId)
    + ToDto(User user)
}

UsersController -> UserService
UserService --> UserMapper : uses
UserService -> UserDTO : creates

UserMapper <-- UserDTO : receives
UserMapper --> User : creates

User --> UserId : has a
User --> Username : has a
User --> UserEmail : has a
User --> UserRole : has a
User --> Password : has a

UserService --> UserRepository
UserRepository --|> BaseRepository
UserRepository -|> IUserRepository

@enduml