 @startuml
autonumber

title BackEnd Process View

participant "FrontEnd" as FE
participant "Controllers" as CN
participant "Services" as SV
participant "Repositories" as REPO
participant "Mappers" as MP
participant "DTOs" as DTO
database "SQL Database" as SQL

activate FE

    FE -> CN : GET /Patients/id
    activate CN
        
        CN -> SV : GetByIdAsync(id)
        activate SV
        
            SV -> REPO : GetByIdAsync(id)
            activate REPO
            
                REPO -> SQL : SELECT * FROM Patients WHERE ID = id
                activate SQL
                
                    SQL --> REPO : returns Patient
                deactivate SQL
            
                REPO --> SV : returns Patient
            deactivate REPO
            
            SV -> MP : ToDTO(Patient)
            activate MP
            
                MP -> DTO : Create(Patient)
                activate DTO
                
                    DTO --> MP : returns PatientDTO
                deactivate DTO
            
                MP --> SV : returns PatientDTO
            deactivate MP
        
            SV --> CN : returns PatientDTO
        deactivate SV
        
        CN --> FE : returns PatientDTO
    deactivate CN

deactivate FE

@enduml