@startuml
autonumber

Title "Backend Process View"

participant "FrontEnd" as FE
participant "<<Controller>>\nStaffController" as C
participant "<<Application>>\nStaffService" as S
participant "<<Mappers>>\nStaffMapper" as M
participant "<<DTO>>\nStaffDto" as DTO
participant "<<Repositories>>\nStaffRepository" as R
database "SQL Database" as SQL

activate FE

FE -> C : GET /staff/id

activate C

    C -> S : GetByIdAsync(id)
    
    activate S
    
    S -> R : GetByIdAsync(id)
    
    activate R
    
    R -> SQL : SELECT * FROM staffs WHERE StaffID = id
    
    activate SQL
    
    SQL --> R : staff
    
    deactivate SQL 
    
    R --> S : staff
    
    deactivate R
    
    S -> M : ToDTO(staff)
    
    activate M
    
    M -> DTO : Create(staff)
    
    activate DTO
    
    DTO --> M : StaffDto
    
    deactivate DTO 
    
    M --> S : StaffDto
    
    deactivate M
    
    S --> C : StaffDto
    
    deactivate S
    
    C --> FE : StaffDto
    
deactivate C

deactivate FE 

@enduml