 @startuml
autonumber

title BackEnd Process View

participant "FrontEnd" as FE
participant "Controllers" as CN
participant "Services" as SV
participant "Repositories" as REPO
participant "Mappers" as MP
participant "DTOs" as DTO
database "SQL Database" as SQL

activate FE

    FE -> CN : GET /Patients
    activate CN
        
        CN -> SV : GetAllAsync()
        activate SV
        
            SV -> REPO : GetAllAsync()
            activate REPO
            
                REPO -> SQL : SELECT * FROM Patients
                activate SQL
                
                    SQL --> REPO : returns List<Patients>
                deactivate SQL
            
                REPO --> SV : returns List<Patients>
            deactivate REPO
            
            SV --> CN : returns List<PatientDTO>
        
            SV -> MP : ToDTO(List<Patients>)
            activate MP   
loop for all operation types
                MP -> DTO : Create(Patient)
                activate DTO
                
                    DTO --> MP : returns PatientDTO
                deactivate DTO
end loop
                  
                MP --> SV : returns List<PatientDTO>
            deactivate MP
            
            SV --> CN : returns List<PatientDTO>
        deactivate SV
        
        CN --> FE : returns List<PatientDTO>  
    deactivate CN
    
    FE -> CN : filters patient profiles
    activate CN 
    
        CN -> SV : FilterOperationTypesAsync(list)
        activate SV
        
            SV --> CN : returns List<OperationTypeDTO>
        deactivate SV
        
        CN --> FE : returns List<OperationTypeDTO>
    deactivate CN

deactivate FE

@enduml