@startuml
autonumber

Title "UC27 - Remove an operation request"

participant "FrontEnd" as FE
participant "<<Controller>>\nOperationRequestController" as CN
participant "<<Application>>\nOperationRequestService" as SV
participant "<<Domain>>\nOperationRequest" as DM
participant "<<Repositories>>\nOperationRequestRepository" as REPO
database "SQL Database" as SQL

activate FE

FE -> CN  : GET /OperationRequests

activate CN

CN -> SV: GetAllAsync()

activate SV

            note left of SV
                Process documented on UC28
            end note

SV --> CN : List<OperationRequestDTO>

deactivate SV

CN --> FE : List<OperationRequestDTO>

deactivate CN

FE -> CN : INACTIVATE /operationRequest/{id}

activate CN

CN -> SV : INACTIVATE /operationRequest/{id}

activate SV

SV -> DM : Deactivate(OperationRequest)

activate DM

DM --> SV : updated operation request 

deactivate DM

SV -> REPO : InactivateAsync(OperationRequest)

activate REPO

REPO -> SQL : INACTIVATE /operationRequest/{id}

activate SQL

SQL --> REPO : operation success

deactivate SQL 

REPO  --> SV : operation success

deactivate REPO

SV --> CN : operation success

deactivate  SV

CN --> FE : operation success

deactivate CN 

deactivate FE

@enduml