@startuml
autonumber

title BackEnd Process View

participant "FrontEnd" as FE
participant "Controllers" as CN
participant "Services" as SV
participant "DTOs" as DTO
participant "Mappers" as MP
participant "Domain" as DM
participant "Repositories" as REPO
database "SQL Database" as SQL

activate FE
    FE -> CN: POST /patients (with data)
    activate CN
    
        CN -> SV : Create(PatientDTO)
        activate SV
        
            SV -> DTO : Create(PatientDTO)
            activate DTO
            
alt Patient data is valid
            
                DTO --> SV : returns PatientDTO
            deactivate DTO
            
            SV -> MP : MapToDomain(PatientDTO)
            activate MP
            
                MP -> DM : Create(Patient)
                activate DM
                     
                    DM --> MP : returns Patient
                deactivate DM
            
                MP --> SV : returns Patient
            deactivate MP
                
            SV -> REPO : AddAsync(Patient)
            activate REPO
            
                REPO -> SQL : POST /patients (Patient)
                activate SQL
                
                    SQL --> REPO : success: created patient (returns user ID)
                deactivate SQL
                
                REPO --> SV : success: created patient (returns user ID)
            

            SV --> CN : success: created patient (returns user ID) 
        FE <-- CN: success: created patient (returns user ID) 

else Patient data is invalid

                REPO -> SQL : POST /patients (User)
                activate SQL
                
                    SQL --> REPO : error: patient already exists
                deactivate SQL
                
        REPO --> SV : error: patient already exists
            deactivate REPO
            SV --> CN : error: patient already exists
        deactivate SV
        FE <-- CN: error: patient already exists
    deactivate CN     
               
deactivate FE
end

@enduml