@startuml
autonumber

actor "Admin" as USER

participant "FrontEnd" as FE
participant "BackEnd" as BE

activate USER

    USER -> FE: wants to list patient profiles 
    activate FE
    
        FE -> BE : GET /Patients
        activate BE
        
            BE --> FE : returns patients
        deactivate BE 
        
alt Couldn't Find Patient Profile
        
        FE --> USER :  informs error with suggestion

else Patient Profile Listed Successfully
        FE --> USER : offers filtering options
    deactivate FE
        
    USER -> FE : selects filter or no filter
    activate FE
    
        FE -> BE : filters patient profiles 
        activate BE 
        
            BE --> FE : returns filtered patient profiles
        deactivate BE
        FE --> USER : lists patient profiles 
    deactivate FE
end
deactivate USER
@enduml
