@startuml
autonumber

Title "UC28 - Search operation requests"

actor "Doctor" as D
participant "FrontEnd" as FE
participant "BackEnd" as BE

activate D

D -> FE: requests to search for operation requests

    activate FE
    
    FE -> BE : GET /operationRequests{id}
    
    alt the requested operation request exists
    
    activate BE
    
    BE --> FE : required operation request \n (eg., patient name, operation type, status)
    
    
    FE --> D: shows the operation request's details \n (eg., patient name, operation type, status)
    
    else 
    
    BE --> FE : error message
    
    deactivate BE
    
    FE --> D : shows error message
    
    deactivate FE 
    
    end
    
deactivate D

@enduml