@startuml
autonumber

actor "Admin" as USER
participant "<<System>>\n SurgicalSync" as SYSTEM

activate USER

    USER -> SYSTEM: wants to edit a staff profile
    activate SYSTEM

        SYSTEM --> USER : shows the list of staff profiles
    deactivate SYSTEM
        
    USER -> SYSTEM : selects the staff profile
    activate SYSTEM
    
    SYSTEM --> USER : show staff profile's data
    deactivate SYSTEM
    
    loop 
    USER-> SYSTEM : selects the data to edit
    activate SYSTEM
    
    SYSTEM --> USER: request data
    
        alt diferent data
            USER <-- SYSTEM : success: staff profile edited
        else same data
            USER <-- SYSTEM : error: date edited same as previous
        end
    deactivate SYSTEM
    
    end 
deactivate USER
@enduml