@startuml
autonumber

actor "Admin" as USER

participant "FrontEnd" as FE
participant "BackEnd" as BE
participant "SMTP API" as EMAIL


activate USER

    USER -> FE: wants to edit user profile
    activate FE

        FE --> USER : requests data (id, name, email)
    deactivate FE
        
    USER -> FE : provides data
    activate FE
        
    alt Email is being altered
        FE --> USER : asks to confirm email
    deactivate FE
    
    USER -> FE : confirms email
    activate FE
    
    else Email is not being altered
    alt user profile was found
        FE -> BE : PUT/users/id (with given data)
        activate BE
            
            BE -> EMAIL : send email notification
            activate EMAIL
                        
                EMAIL --> BE : email sent
            deactivate EMAIL
                        
            BE --> FE : success: edited user profile
                           
        USER <-- FE : success: user profile updated
        
    else user profile not found
            
            BE --> FE : error: user profile was not found
        deactivate BE
        
        USER <-- FE : error : user profile was not found
    end
    
    end
    deactivate FE
    
deactivate USER

@enduml