@startuml
autonumber

actor "Admin" as USER
participant "<<System>>\n SurgicalSync" as SYSTEM

activate USER

    USER -> SYSTEM: wants to search for operation types
    activate SYSTEM
    
        SYSTEM --> USER : asks for operation type id
    deactivate SYSTEM 
       
    USER -> SYSTEM: provides operation type id
    activate SYSTEM

        alt Couldn't Find Operation Type
            USER <-- SYSTEM : informs error with suggestion
        else Operation Type Found
            SYSTEM --> USER : shows operation type
        end
        
    deactivate SYSTEM
    
deactivate USER
@enduml