@startuml
autonumber

actor "Admin" as USER

participant "FrontEnd" as FE
participant "BackEnd" as BE

activate USER
    
    
     USER -> SYSTEM: wants to edit a staff profile
  
        activate SYSTEM
    
            SYSTEM --> USER : asks to select a profile and request data
        deactivate SYSTEM
    USER -> FE : provides staffID and information to change
    activate FE
    
    alt staff and data are valid

    FE -> BE : PUT /staff/id ( with staff profile information)
    activate BE
    
    BE --> FE : return operation success
    deactivate BE
    
    FE --> USER: operation success
    
    else staff doesn't exist or data is not correct
    
    FE --> USER: error: staff doesn't exist or data is not correct
    
    end 
deactivate USER

@enduml