@startuml
autonumber

title BackEnd Process View

participant "FrontEnd" as FE
participant "Controllers" as CN
participant "Services" as SV
participant "DTOs" as DTO
participant "Mappers" as MP
participant "Domain" as DM
participant "Repositories" as REPO
database "SQL Database" as SQL

activate FE
    
        FE -> CN : PUT /staff (with given data)
        activate CN
        
        CN -> SV: Create(StaffDto)
        activate SV
        
        SV -> DTO: Create(StaffDto) 
        activate DTO
                        
                DTO --> SV : returns StaffDto
            deactivate DTO
            
            SV -> MP : MapToDomain(StaffDto)
            activate MP
            
                MP -> DM : Create(Staff)
                activate DM
                     
                    DM --> MP : returns staff
                deactivate DM
            
                MP --> SV : returns staff
            deactivate MP
                
            SV -> REPO : UpdateAsync(staff)
            activate REPO
            
            alt Staff  data is valid and staff exist

                REPO -> SQL : PUT /staff (with given data)))
                activate SQL
                
                    SQL --> REPO : success: edited staff profile 
                deactivate SQL
                
                REPO --> SV : success: added staff profile 
                deactivate REPO

            SV --> CN : success: edited staff profile 
        FE <-- CN: success: edited staff profile 

else Staff  data isn't valid or staff doesn't exist

               
        
            SV --> CN : error: Wrong format of parameters
        deactivate SV
        FE <-- CN: error: Wrong format of parameters
    deactivate CN     
               
deactivate FE
end

@enduml