@startuml
autonumber

title BackEnd Process View

participant "FrontEnd" as FE
participant "Controllers" as CN
participant "Services" as SV
participant "DTOs" as DTO
participant "Mappers" as MP
participant "Domain" as DM
participant "Repositories" as REPO
database "SQL Database" as SQL

activate FE
    FE -> CN: POST /operation-types (with given data)
    activate CN
    
        CN -> SV : Create(OperationTypeDTO)
        activate SV
        
            SV -> DTO : Create(OperationTypeDTO)
            activate DTO
            
alt User data is valid
            
                DTO --> SV : returns OperationTypeDTO
            deactivate DTO
            
            SV -> MP : MapToDomain(OperationTypeDTO)
            activate MP
            
                MP -> DM : Create(OperationType)
                activate DM
                     
                    DM --> MP : returns OperationType
                deactivate DM
            
                MP --> SV : returns OperationType
            deactivate MP
                
            SV -> REPO : AddAsync(OperationType)
            activate REPO
            
                REPO -> SQL : POST /operation-types (OperationType)
                activate SQL
                
                    SQL --> REPO : success: added operation type (returns ID)
                deactivate SQL
                
                REPO --> SV : success: added operation type (returns ID)
            

            SV --> CN : success: added operation type (returns ID)
        FE <-- CN: success: added operation type (returns ID) 

else User data is invalid

                REPO -> SQL : POST /operation-types (OperationType)
                activate SQL
                
                    SQL --> REPO : error: operation type already exists
                deactivate SQL
                
        REPO --> SV : error: operation type already exists
            deactivate REPO
            SV --> CN : error: operation type already exists
        deactivate SV
        FE <-- CN: error: operation type already exists
    deactivate CN     
               
deactivate FE
end

@enduml