@startuml
skinparam packageStyle rectangle

skinparam rectangle {
    BorderColor black
}

left to right direction

skinparam actor {
    BackgroundColor LightBlue
    BorderColor Blue
    FontColor Black
}

actor "Admin" as A #LightBlue
actor "BackofficeUser" as BU #LightGreen
actor "Patient" as P #Yellow
actor "Doctor" as D #Red
actor "Non-authenticated Backoffice User" as NA #Violet

title "Use Case Diagram"

rectangle "System" as SYS {

    usecase "UC01 - Register new backoffice user via an out-of-band process"
    usecase "UC02 - Reset my password if I forget it"
    usecase "UC03 - Register for the health care application"
    usecase "UC04 - Create a user profile"
    usecase "UC05 - Book appointments online"
    usecase "UC06 - Update user profile"
    usecase "UC07 - Delete my account and all associated data"
    usecase "UC08 - Log in to the System using my credentials"
    usecase "UC09 - Role-based access control"
    usecase "UC10 - Log in to the system using the IAM credentials"
    usecase "UC11 - Access my features"
    usecase "UC12 - Create new patient profile"
    usecase "UC13 - Edit patient profile"
    usecase "UC14 - Delete a patient profile"
    usecase "UC15 - List patient profiles"
    usecase "UC16 - Search patient profiles"
    usecase "UC17 - See patient details"
    usecase "UC18 - Create a new staff profile"
    usecase "UC19 - Edit a staff profile"
    usecase "UC20 - Deactivate a staff profile"
    usecase "UC21 - List staff profiles"
    usecase "UC22 - Search staff profiles"
    usecase "UC23 - See staff details"
    usecase "UC24 - Request an operation"
    usecase "UC25 - Update an operation requisition"
    usecase "UC26 - Remove an operation requisition"
    usecase "UC27 - List operation requisitions"
    usecase "UC28 - Search operation requisitions"
    usecase "UC29 - See operation requests details"
    usecase "UC30 - Add new types of operations"
    usecase "UC31 - Edit existing operation types"
    usecase "UC32 - Remove operation types"
    usecase "UC33 - List operation types"
    usecase "UC34 - Search operation types"
    usecase "UC35 - See operation type details"
    
    A --> "UC01 - Register new backoffice user via an out-of-band process"
    A --> "UC12 - Create new patient profile"
    A --> "UC13 - Edit patient profile"
    A --> "UC14 - Delete a patient profile"
    A --> "UC15 - List patient profiles"
    A --> "UC16 - Search patient profiles"
    A --> "UC17 - See patient details"
    A --> "UC18 - Create a new staff profile"
    A --> "UC19 - Edit a staff profile"
    A --> "UC20 - Deactivate a staff profile"
    A --> "UC21 - List staff profiles"
    A --> "UC22 - Search staff profiles"
    A --> "UC23 - See staff details"
    A --> "UC30 - Add new types of operations"
    A --> "UC31 - Edit existing operation types"
    A --> "UC32 - Remove operation types"
    A --> "UC33 - List operation types"
    A --> "UC34 - Search operation types"
    A --> "UC35 - See operation type details"
    
    BU --> "UC02 - Reset my password if I forget it"
    
    P --> "UC03 - Register for the health care application"
    P --> "UC04 - Create a user profile"
    P --> "UC05 - Book appointments online"
    P --> "UC06 - Update user profile"
    P --> "UC07 - Delete my account and all associated data"
    P --> "UC10 - Log in to the system using the IAM credentials"
    P --> "UC11 - Access my features"
    
    NA --> "UC08 - Log in to the System using my credentials"
    NA --> "UC09 - Role-based access control"
    
    D --> "UC24 - Request an operation"
    D --> "UC25 - Update an operation requisition"
    D --> "UC26 - Remove an operation requisition"
    D --> "UC27 - List operation requisitions"
    D --> "UC28 - Search operation requisitions"  
    D --> "UC29 - See operation requests details" 
}

@enduml