@startuml
autonumber

actor "Admin" as USER
participant "<<System>>\n SurgicalSync" as SYSTEM

activate USER

    
    USER -> SYSTEM : selects and write attributes\n( name/email/specialization) to search
    activate SYSTEM
    
   alt staff profiles with this attributes
            USER <-- SYSTEM : success: list of staff profiles that fit the attributes
        else none staff profile fit  attributes 
            USER <-- SYSTEM : error: none staff profile fit  attributes 
        end
    deactivate SYSTEM
    
     
deactivate USER
@enduml