@startuml
autonumber

Title "UC29 - See details of an operation request"

actor "Doctor" as D
participant "FrontEnd" as FE
participant "BackEnd" as BE

activate D

D -> FE: requests to see the details \nof an operation request 

    activate FE
    
    FE -> BE : GET /operationRequests
    
    activate BE
    
    BE --> FE : list of operationRequests
    
    deactivate BE
    
    FE --> D : shows the list of all the operation \n requests and asks for the id
    
    deactivate FE
    
    D -> FE : Inserts the id
    
    alt the requested operation exists
    
    activate FE
    
    FE -> BE : GET /operationRequests/{id}
    
    activate BE
    
    BE --> FE : operationRequests details (eg., operationRequisitionId, \n DeadlineDate, Priority, OperationType and PatientNumber)
    
    deactivate BE
    
    FE --> D: shows the operation request's details \n (eg., operationRequisitionId, DeadlineDate, Priority \n OperationType and PatientNumber) 
        
    else
    
    FE --> D : shows error message
    
    deactivate FE
    
    end   
    
deactivate D

@enduml