@startuml
autonumber

Title "UC30 - See details of an operation request"

actor "Doctor" as D
participant "<<System>> \n SurgicalSync" as SYSTEM

activate D

D -> SYSTEM: requests to see the details \n of an operation request

    activate SYSTEM
    
    SYSTEM --> D: shows the list of all the operation \n requests and asks for the id 
    
    deactivate SYSTEM
    
    D -> SYSTEM : Inserts the id

    alt the requested operation request exists 
    
    activate SYSTEM
    
    SYSTEM --> D: shows the operation request's details \n (eg., operationRequisitionId, DeadlineDate, Priority \n OperationType and PatientNumber)

    else
    
    SYSTEM --> D : shows error message
    
    deactivate SYSTEM
    
    end
    
deactivate D

@enduml