@startuml
autonumber

actor "Admin" as USER

participant "FrontEnd" as FE
participant "BackEnd" as BE

activate USER

    USER -> FE : wants to remove staff profile from hospital's active roster
    activate FE
    
    FE -> BE : GET /staff
    activate BE
    
    BE --> FE : return list of staff profiles active in hospital's roster
    deactivate BE
    
    FE --> USER : shows list of staff profiles and asks to select one
    deactivate FE

    USER -> FE : selects a staff profile 
    activate FE
    
    FE -> BE  : DELETE /staff(id)
    activate BE
    
   BE --> FE : return operation's success
   deactivate BE
   
   FE --> USER : shows operation's success
deactivate USER

@enduml