@startuml
autonumber

Title "UC32 - Remove an operation requisition"

actor "Doctor" as D
participant "<<System>> \n SurgicalSync" as SYSTEM
participant "<<Planning Module>>" as PLANNING

activate D

D -> SYSTEM: asks to remove an operation requisition

activate SYSTEM

SYSTEM --> D: asks for the ID of the requisition to be 

deactivate SYSTEM

D -> SYSTEM : Inserts the operation requisition ID

activate SYSTEM

alt the logged in doctor is the one who created the operation \n request and the operation is not yet scheduled

SYSTEM --> D : shows confirmation prompt

deactivate SYSTEM

D -> SYSTEM : confirms deletion

activate SYSTEM

SYSTEM -> SYSTEM : removes the operation request \n from the patient's medical record

SYSTEM -> SYSTEM : logs the deletion action

SYSTEM --> D: shows operation success

SYSTEM -> PLANNING : notify to update schedules

else The doctor is not authorized to delete the request

SYSTEM --> D: shows error message 

deactivate SYSTEM

end 

deactivate D

@enduml