@startuml
autonumber

actor "Admin" as USER

participant "FrontEnd" as FE
participant "BackEnd" as BE

activate USER

    USER -> FE : wants to see staff profile details
    activate FE
    
    FE -> BE : GET /staff
    activate BE
    
    BE --> FE : return list of staff profiles 
    deactivate BE
    
    FE --> USER : shows list of staff profiles and asks to select one
    deactivate FE

    USER -> FE : selects a staff profile 
    activate FE
    
    FE -> BE  : GET /staff7(id)
    activate BE
    
   BE --> FE : return staff profile information
   deactivate BE
   
   FE --> USER : shows staff details
deactivate USER

@enduml