@startuml
autonumber

actor "Admin" as USER
participant "<<System>>\n SurgicalSync" as SYSTEM
participant "SMTP API" as EMAIL

activate USER

    USER -> SYSTEM: wants to edit user profile
    activate SYSTEM

        SYSTEM --> USER : requests data (id,name, email)
    deactivate SYSTEM
        
    USER -> SYSTEM : provides data
    activate SYSTEM
        
    alt Email is being altered
        SYSTEM --> USER : asks to confirm email
    deactivate SYSTEM
    
    USER -> SYSTEM : confirms email
    activate SYSTEM
    
    else Email is not being altered
    
    alt user profile was found

        SYSTEM -> EMAIL : sends email notification
        activate EMAIL
        
            EMAIL --> SYSTEM : email sent
        deactivate EMAIL
        USER <-- SYSTEM : success: user details updated
        
    else user profile not found
    
        USER <-- SYSTEM : error: user profile not found
    end
    
    end
    deactivate SYSTEM
    
deactivate USER
@enduml