@startuml
autonumber

Title "UC34 - Search operation requisitions"

actor "Doctor" as D
participant "<<System>> \n SurgicalSync" as SYSTEM

activate D

D -> SYSTEM: requests to search for operation requisitions

    alt the requested operation requisition exists 
    
    activate SYSTEM
    
    SYSTEM --> D: shows the operation requisition's details \n (eg., patient name, operation type, status)

    
    else
    
    SYSTEM --> D : shows error message
    
    deactivate SYSTEM
    
    end
    
deactivate D

@enduml