@startuml
autonumber

actor "Admin" as USER

participant "FrontEnd" as FE
participant "BackEnd" as BE
participant "Firebase IAM API" as FIREBASE
participant "SMTP API" as EMAIL

activate USER

    USER -> FE : wants to create a backoffice user
    activate FE
    
        FE --> USER : requests data (username, email, role)
    deactivate FE

    USER -> FE : provides data
   
        activate FE
        
            alt User Already Exists
               
            FE -> BE : POST /users
            activate BE
            
                BE --> FE : error: user already exists
            deactivate BE 
            FE --> USER : informs error with suggestion
            
            else User Created Successfully
            
            FE -> BE : POST /users
            activate BE
            
                BE -> FIREBASE : create user
                activate FIREBASE 
                
                    FIREBASE --> BE : success: created user
                deactivate FIREBASE
                
                BE -> EMAIL : send email to setup password
                activate EMAIL
                
                    EMAIL --> BE : email sent
                deactivate EMAIL
            
                BE --> FE : success: created user (returns user ID)
            deactivate BE
               
            FE --> USER : shows created user
        deactivate FE
    end
            
deactivate USER

@enduml