@startuml
autonumber

actor "Admin" as USER
participant "<<System>>\n Hospital" as SYSTEM

activate USER

    USER -> SYSTEM: wants to create a backoffice user
    activate SYSTEM

        SYSTEM --> USER : requests data (username, email, role)
    deactivate SYSTEM
        
    USER -> SYSTEM : provides data
    activate SYSTEM
        alt User Already Exists
           USER <-- SYSTEM : informs error with suggestion
        else User Created Successfully
           USER <-- SYSTEM : shows created user
        end
    deactivate SYSTEM
    
deactivate USER
@enduml