@startuml
autonumber

actor "Admin" as USER
participant "<<System>>\n SurgicalSync" as SYSTEM

activate USER

    USER -> SYSTEM: wants to remove a staff profile
    activate SYSTEM

        SYSTEM --> USER : show list of staff profiles in the hospital's active roster
    deactivate SYSTEM
        
    USER -> SYSTEM : selects a staff profile
    activate SYSTEM
    
    SYSTEM --> USER: removes the staff profile from the active roster, \n but their historical data remains accessible.
    
    alt sucess operation
    SYSTEM --> USER: show sucess of operation
    
    else not records the action for audit purposes
   SYSTEM --> USER: ERROR! Not records the action for audit purposes  or/and their historical data  


  
    end 
  
deactivate USER
@enduml