@startuml
autonumber

actor "Admin" as USER
participant "<<System>>\n SurgicalSync" as SYSTEM

activate USER

    USER -> SYSTEM: wants to edit a patient profile
    activate SYSTEM

        SYSTEM --> USER : lists all patient profiles and asks to select one
    deactivate SYSTEM
        
    USER -> SYSTEM : selects patient profile
    activate SYSTEM
    
        SYSTEM --> USER: shows fields of profile that can be edited
    deactivate SYSTEM
    
    loop Selects a field to edit
    
        USER -> SYSTEM: gives information to replace
        activate SYSTEM
        
            SYSTEM --> USER: updates information
    end
    
    USER <-- SYSTEM : success: confirms operation success
    deactivate SYSTEM
    
deactivate USER
@end