@startuml
autonumber

actor "Admin" as USER
participant "<<System>>\n SurgicalSync" as SYSTEM

activate USER

    USER -> SYSTEM: wants to see patient details
    activate SYSTEM

        alt patient was found
            SYSTEM --> USER : success: returns patient details
            
        else patient not found
            SYSTEM --> USER : error: patient not found
        end
    deactivate SYSTEM
    
deactivate USER
@enduml