@startuml
autonumber

title "UC28 - Search for an operation request"

participant "FrontEnd" as FE
participant "<<Controller>>\nOperationRequestController" as C
participant "<<Application>>\nOperationRequestService" as S
participant "<<Application>>\nPatientNameMicroService" as P
participant "<<Mappers>>\nOperationRequestMapper" as M
participant "<<DTO>>\nOperationRequestDTO" as DTO
participant "<<Repositories>>\nOperationRequestRepository" as R
participant "<<Repositories>>\nPatientRepository" as RP
database "SQL Database" as SQL

activate FE

alt doctor chooses to search by id

FE -> C : GET /operationRequest?operationRequestId={id}

activate C

    C -> S : GetByIdAsync(id)
    
    activate S
    
    S -> R : GetByIdAsync(id)
    
    activate R
    
    R -> SQL : SELECT * FROM operationRequests WHERE ID = id
    
    activate SQL
    
    SQL --> R : OperationRequest
    
    deactivate SQL 
    
    R --> S : OperationRequest
    
    deactivate R
    
    S -> M : ToDTO(OperationRequest)
    
    activate M
    
    M -> DTO : Create(OperationRequest(operationRequestId, priority, deadlineDate,\n operationTypeId, LicenseNumber, MedicalRecordNumber))
    
    activate DTO
    
    DTO --> M : OperationRequestDTO
    
    deactivate DTO 
    
    M --> S : OperationRequestDTO
    
    deactivate M
    
    S --> C : OperationRequestDTO
    
    deactivate S
    
    C --> FE : OperationRequestDTO
    
deactivate C

else doctor chooses to search by patientName filter

FE -> C : GET /operationRequest?patientName={patientName}

activate C

    C -> S : GetAllByPatientName(patientName)
    
    activate S
    
    S -> P : GetAllOperationRequestsByPatientName(patientName)
    
    activate P
    
    P -> RP : GetPatientByPatientName(patientName)
    
    activate RP
    
    RP -> SQL : SELECT * FROM Patients WHERE PatientName = patientName
    
    activate SQL
    
    SQL --> RP : Patient
    
    deactivate SQL
    
    RP --> P : Patient
    
    deactivate RP
    
    P -> RP : GetMedicalRecordNumber(Patient)
    
    activate RP
    
    RP -> SQL : GetMedicalRecordNumber(Patient)
    
    activate SQL
    
    SQL --> RP : MedicalRecordNumber
    
    deactivate SQL
    
    RP --> P : MedicalRecordNumber
    
    deactivate RP 
    
    P -> R : GetByMedicalRecordNumber(medicalRecordNumber)
    
    activate R
    
    R -> SQL : SELECT * FROM OperationRequests WHERE MedicalRecordNumber = medicalRecordNumber
    
    activate SQL
    
    SQL --> R : List<OperationRequest> operationRequests
    
    deactivate SQL
    
    R --> P : List<OperationRequest> operationRequests
    
    deactivate R
    
    P -> M : ToListDTO(operationRequests)
        
        loop for all the Operation Requests on the list
        
        activate M
        
        M -> DTO : Create(OperationRequest(operationRequestId, priority, deadlineDate,\n operationTypeId, LicenseNumber, MedicalRecordNumber))
        
        activate DTO
        
        DTO --> M : OperationRequestDTO
        
        deactivate DTO 
    
        end
    
   M --> P : List<OperationRequestDTO> operationRequestDtos
   
   deactivate M
   
   P --> S : List<OperationRequestDTO> operationRequestDtos
   
   deactivate P
   
   S --> C : List<OperationRequestDTO> operationRequestDtos
   
   deactivate S
   
   C --> FE : List<OperationRequestDTO> operationRequestDtos
    
deactivate C

else doctor chooses to search by medicalRecordNumber filter

FE -> C : GET /operationRequest?medicalRecordNumber={medicalRecordNumber}

activate C

    C -> S : GetAllByMedicalRecordNumber(medicalRecordNumber)
    
    activate S
    
    S -> R : GetAllByMedicalRecordNumber(medicalRecordNumber)
    
    activate R
    
    R -> SQL : SELECT * FROM operationRequests WHERE MedicalRecordNumber = medicalRecordNumber
    
    activate SQL
    
    SQL --> R : list<OperationRequest> operationRequests
    
    deactivate SQL 
    
    R --> S : list<OperationRequest> operationRequests
    
    deactivate R
    
    S -> M : ToListDTO(operationRequests)
    
    loop for all the Operation Requests on the list
    
    activate M
    
    M -> DTO : Create(OperationRequest(operationRequestId, priority, deadlineDate,\n operationTypeId, LicenseNumber, MedicalRecordNumber))
    
    activate DTO
    
    DTO --> M : OperationRequestDTO
    
    deactivate DTO 

    end
        
    M --> S : List<OperationRequestDTO> OperationRequestsDto
    
    deactivate M
    
    S --> C : List<OperationRequestDTO> OperationRequestsDto
    
    deactivate S
    
    C --> FE : List<OperationRequestDTO> OperationRequestsDto
    
deactivate C

else doctor chooses the search by operationType filter

FE -> C : GET /operationRequest?operationTypeId={id}

activate C

    C -> S : GetAllByOperationType(id)
    
    activate S
    
    S -> R : GetAllByOperationType(id)
    
    activate R
    
    R -> SQL : SELECT * FROM operationRequests WHERE OperationRequestId = id
    
    activate SQL
    
    SQL --> R : list<OperationRequest> operationRequests
    
    deactivate SQL 
    
    R --> S : list<OperationRequest> operationRequests
    
    deactivate R
    
    S -> M : ToListDTO(operationRequests)
    
    loop for all the Operation Requests on the list
    
    activate M
    
    M -> DTO : Create(OperationRequest(operationRequestId, priority, deadlineDate,\n operationTypeId, LicenseNumber, MedicalRecordNumber))
    
    activate DTO
    
    DTO --> M : OperationRequestDTO
    
    deactivate DTO 
    
    end 
    
    M --> S : List<OperationRequestDTO> OperationRequestsDto
    
    deactivate M
    
    S --> C : List<OperationRequestDTO> OperationRequestsDto
    
    deactivate S
    
    C --> FE : List<OperationRequestDTO> OperationRequestsDto
    
deactivate C

else doctor chooses to search by dateRange filter

FE -> C : GET /operationRequest?startDate={YYYY-mm-dd}&endDate={YYYY-mm-dd}

activate C

    C -> S : GetAllInsideDateRange(startDate, endDate)
    
    activate S
    
    S -> R : GetAllInsideDateRange(startDate, endDate)
    
    activate R
    
    R -> SQL : SELECT * FROM operationRequests WHERE DeadlineDate >= startDate && DeadlineDate <= endDate
    
    activate SQL
    
    SQL --> R : list<OperationRequest> operationRequests
    
    deactivate SQL 
    
    R --> S : list<OperationRequest> operationRequests
    
    deactivate R
    
    S -> M : ToListDTO(operationRequests)
    
    loop for all the Operation Requests on the list
    
    activate M
    
    M -> DTO : Create(OperationRequest(operationRequestId, priority, deadlineDate,\n operationTypeId, LicenseNumber, MedicalRecordNumber))
    
    activate DTO
    
    DTO --> M : OperationRequestDTO
    
    deactivate DTO 
    
    end 
    
    M --> S : List<OperationRequestDTO> OperationRequestsDto
    
    deactivate M
    
    S --> C : List<OperationRequestDTO> OperationRequestsDto
    
    deactivate S
    
    C --> FE : List<OperationRequestDTO> OperationRequestsDto
    
deactivate C

end 

deactivate FE 

@enduml