@startuml
autonumber

Title "UC25 - List staff profiles"

participant "FrontEnd" as FE
participant "Controllers" as C
participant "Services" as S
participant "Repositories" as R
participant "Mappers" as M
participant "DTOs" as DTO
database "SQL Database" as SQL

activate FE

FE -> C : GET /staff

    activate C
    
    C -> S : GetAllAsync()
    
    activate S
    
    S -> R : GetAllAsync()
    
    activate R
    
    R -> SQL : SELECT * FROM StaffProfiles
    
    activate SQL
    
    SQL --> R : List<StaffProfiles>
    
    deactivate SQL
    
    R --> S : List<StaffProfiles>
    
    deactivate R
    
    S -> M : ToDto(List<StaffProfiles> list)
    
    activate M
    
    loop for all the list's members
    
    M -> DTO : Create(StaffProfile)
    
    activate DTO
    
    DTO --> M : StaffProfileDTO
    
    deactivate DTO
    
    end
    
    M --> S : List<StaffProfileDTO>
    
    deactivate M 
    
    S --> C : List<StaffProfileDTO>
    
    deactivate S
    
    C --> FE : List<StaffProfileDTO>
    
    deactivate C 
    
    alt The doctor applies a filter
    
    FE -> C : filters operation requisitions
    
    activate C
    
    C -> S : FilterOperationRequisitionsAsync(list)
    
    activate S
    
    S -->C : List<OperationRequestDTO>
    
    deactivate S 
    
    C --> FE : List<OperationRequestDTO>
    
    deactivate C 
    
    end 
    
deactivate FE 

@enduml