@startuml
autonumber

actor "Admin" as USER
participant "<<System>>\n SurgicalSync" as SYSTEM
participant "Firebase IAM API" as FIREBASE
participant "SMTP API" as EMAIL

activate USER

    USER -> SYSTEM: wants to create a backoffice user
    activate SYSTEM

        SYSTEM --> USER : requests data (username, email, role)
    deactivate SYSTEM
        
    USER -> SYSTEM : provides data
    
    activate SYSTEM
        alt User Already Exists
           USER <-- SYSTEM : informs error with suggestion
        else User Created Successfully
            SYSTEM -> FIREBASE : creates user (with data)
            
            activate FIREBASE
                FIREBASE --> SYSTEM : user created
            deactivate FIREBASE
            
            SYSTEM -> EMAIL : sends email to setup password
            activate EMAIL
                EMAIL --> SYSTEM : email sent
            deactivate EMAIL
        
           USER <-- SYSTEM : shows created user
        end
    deactivate SYSTEM
    
deactivate USER
@enduml