@startuml
autonumber

actor "Admin" as USER

participant "FrontEnd" as FE
participant "BackEnd" as BE

activate USER


    USER -> FE : selects a staff  to see staff's  details
    activate FE
    
    FE -> BE  : GET /staff/id
    activate BE
    
   BE --> FE : return staff's details
   deactivate BE
   
   FE --> USER : shows staff's details
deactivate USER

@enduml