@startuml
autonumber

title BackEnd Process View

participant "FrontEnd" as FE
participant "Controllers" as CN
participant "Services" as SV
participant "Domain" as DM
participant "Repositories" as REPO
database "SQL Database" as SQL

activate FE
    FE -> CN : GET /operation-types
    activate CN
        
        CN -> SV : GetAllAsync()
        activate SV
        
            note left of SV
                Process documented on use case 40
            end note
            SV --> CN : returns List<OperationTypeDTO>
        deactivate SV
        
        CN --> FE : returns List<OperationTypeDTO>
    deactivate CN

    FE -> CN: DELETE /operationTypes/id
    activate CN
    
        CN -> SV : DELETE /operationTypes/id
        activate SV
        
alt Operation Type Removed Successfully

            SV -> DM : Deactivate(OperationType)
            activate DM
            
                DM --> SV : returns updated OperationType
            deactivate DM
                 
            SV -> REPO : DeleteAsync(OperationType)
            activate REPO
            
                REPO -> SQL : DELETE /operationTypes/id
                activate SQL
                
                    SQL --> REPO : success: removed operation type successfully
                deactivate SQL
                
                REPO --> SV : success: removed operation type successfully
            deactivate REPO
            

            SV --> CN : success: removed operation type successfully
        FE <-- CN: success: removed operation type successfully

else Couldn't Remove Operation Type

            SV --> CN : error: operation type couldn't be removed
        deactivate SV
        FE <-- CN: error: operation type couldn't be removed
    deactivate CN     
               
deactivate FE
end

@enduml