@startuml
autonumber

Title "UC28 - Search operation requests"

actor "Doctor" as D
participant "<<System>> \n SurgicalSync" as SYSTEM

activate D

D -> SYSTEM: requests to search for operation request

    alt the requested operation request exists 
    
    activate SYSTEM
    
    SYSTEM --> D: shows the operation request's details \n (eg., patient name, operation type, status)

    
    else
    
    SYSTEM --> D : shows error message
    
    deactivate SYSTEM
    
    end
    
deactivate D

@enduml