@startuml
'https://plantuml.com/sequence-diagram

Title "UC11 - Access my features"

autonumber

participant "FrontEnd" as FE
participant "<<Controllers>>\nPatientController" as CN
participant "<<Application>>\nPatientService" as SV
participant "<<Repositories>>\nPatientRepository" as REPO
participant "<<Mappers>>\nPatientMapper" as MP
participant "<<DTOs>>\nPatientDto" as DTO
database "SQL Database" as SQL

activate FE

FE -> CN : GET /patients/{id}

activate CN

CN -> SV : GetByIdAsync(id)

activate SV

SV -> REPO : GetByIdAsync(id)

activate REPO

REPO -> SQL : SELECT * FROM Patients WHERE ID = id

activate SQL

SQL --> REPO : Patient

deactivate SQL

REPO --> SV : Patient

deactivate REPO

SV -> MP : ToDTO(Patient)

activate MP

MP -> DTO : Create(Patient)

activate DTO

DTO --> MP : PatientDto 

deactivate DTO 

MP --> SV : PatientDto

deactivate MP

SV --> CN : PatientDto

deactivate SV

CN --> FE : PatientDto

deactivate CN 

deactivate FE 

@enduml