@startuml
autonumber

Title "UC07 - Delete my account and all associated data"

actor "Patient" as P
participant "FrontEnd" as FE
participant "BackEnd" as BE
participant "SMTP API" as EMAIL

activate P

P -> FE: Asks to delete his account \n and all his associated data
    
    activate FE
    
    FE -> BE : asks to send confirmation via email
    
    activate BE
    
    BE -> EMAIL : send email for confirmation
    
    activate EMAIL
    
    EMAIL --> BE : confirmation email
    
    deactivate EMAIL 
    
    BE --> FE : confirmation email
    
    deactivate BE
    
    FE --> P: asks for confirmation via email
    
    deactivate FE
  
    P -> FE: confirms the deletion
    
    alt confirmed deletion
    
    activate FE
    
    FE -> BE : asks to remove the patient data \n following the GDPR specifications
    
    activate BE
    
    BE --> FE : deletion success
    
    deactivate BE
    
    FE -> BE : asks to send email informing \n of the patient data deletion
    
    activate BE
    
    BE -> EMAIL : asks to send email informing \n of the patient data deletion
    
    activate EMAIL 
    
    EMAIL --> BE : email sent
    
    deactivate EMAIL
    
    BE --> FE : email sent
    
    deactivate BE
    
    FE --> P : operation success email
    
    FE -> BE : asks to delete the patient account
    
    activate BE
    
    BE --> FE : operation success
    
    deactivate BE

deactivate P

end 
@enduml