@startuml
autonumber

Title "UC12 - Access Patient Details After Authentication"

actor "Patient" as P
participant "<<System>> \n SurgicalSync" as SYSTEM

activate P 

P -> SYSTEM: asks to access his details

    activate SYSTEM
    
    alt session valid

        SYSTEM --> P: displays the list of the available \n features and asks to select one
        
    deactivate SYSTEM
    
        P -> SYSTEM: selects one of the features
        
    activate SYSTEM
        
        SYSTEM --> P: displays the feature´s information

    else session expired
        SYSTEM --> P: session expired, prompts re-authentication
        
    deactivate SYSTEM

    enD

deactivate P

@enduml
