@startuml
autonumber

Title "UC27 - Remove an operation request"

actor "Doctor" as D 

participant "FrontEnd" as FE
participant "BackEnd" as BE

activate D

D -> FE: asks to remove an operation request

activate FE

FE --> D: asks for the ID of the request to be 

deactivate FE

D -> FE : Inserts the operation request ID

activate FE

alt the logged in doctor is the one who created the operation \n request and the operation is not yet scheduled

FE -> BE: GET /operationRequest/id (with details)

activate BE

BE --> FE: operation request details

deactivate BE

FE --> D : shows the operation request \n details and asks for confirmation

deactivate FE

D -> FE : confirms deletion

activate FE

FE -> BE : DELETE /operationRequest/id

activate BE

BE -> PLANNING : notify to update schedules

activate PLANNING 

PLANNING -> PLANNING : updates the schedules

PLANNING --> BE: confirms that the \n notification was received

deactivate PLANNING

BE --> FE : operation success

deactivate BE

FE --> D: shows operation success

else The doctor is not authorized to delete the request

FE -> BE : GET /operationRequest/id (for validation)

activate BE

BE --> FE : error: unauthorized doctor

deactivate BE

FE --> D: shows error message 

deactivate FE

end 

deactivate D
@enduml