    @startuml

skinparam component {
    FontSize 30
    FontName Courier
    BorderColor Black
    BackgroundColor LightGreen
    ArrowFontName Impact
}

component [<<System>>\nBackoffice\nWebApplication] as COMPONENT {
    component "Controllers" as CONTROLLERS
    component "Services" as SERVICES
    component "Domain" as DOMAIN
    component "Repositories" as REPOSITORIES
    component "DTOs" as DTO
    
}

CONTROLLERS -up- "Backoffice API"
CONTROLLERS -down- SERVICES
SERVICES -down- DOMAIN
SERVICES -down- DTO
SERVICES -right- REPOSITORIES

@enduml