@startuml
autonumber

title BackEnd Process View

participant "FrontEnd" as FE
participant "Controllers" as CN
participant "Services" as SV
participant "DTOs" as DTO
participant "Firebase IAM API" as FIREBASE
participant "SMTP API" as SMTP

activate FE
    FE -> CN: PUT /authentication (with data)
    activate CN
    
        CN -> SV : Create(GoogleLoginDTO)
        activate SV
        
            SV -> DTO : Create(GoogleLoginDTO)
            activate DTO
            
alt Data is valid
            
                DTO --> SV : returns GoogleLoginDTO
            deactivate DTO
            
            SV -> FIREBASE : GivePatientGoogleAuthAsync(url, email)
            activate FIREBASE
            
                FIREBASE --> SV : success: created OAuth URL
            deactivate FIREBASE
            
            SV -> SMTP : SendEmailAsync(email, url)
            activate SMTP
            
                SMTP --> SV : success: email sent
            deactivate SMTP
            
            SV -> FIREBASE : CreateUserAsync(GoogleLoginDTO)
            activate FIREBASE
            
                FIREBASE --> SV : success: created user (returns user ID)
            deactivate FIREBASE

            SV --> CN : success: created patient (returns user ID) 
        FE <-- CN: success: created patient (returns user ID) 

else Data is invalid

            SV --> CN : error: could not create user account
        deactivate SV
        FE <-- CN: error: could not create user account
    deactivate CN     
               
deactivate FE
end

@enduml