@startuml
autonumber

Title "UC28 - List operation requests"

actor "Doctor" as D

participant "FrontEnd" as FE
participant "BackEnd" as BE

activate D

D -> FE: requests to list the operation requests

activate FE

FE -> BE: GET /operationRequests

activate BE

BE --> FE: operation requests

deactivate BE

FE --> D: shows the list of the operation requests \n (with details: patient name, operation type, status) \n and filtering options

deactivate FE

alt The doctor applies a filter

    D -> FE: selects filter options

    activate FE
    
    FE -> BE: GET /operationRequests with filters

    activate BE

    BE --> FE: filtered requests

    deactivate BE

    FE --> D: displays the filtered list

    deactivate FE

end

deactivate D

@enduml