@startuml
autonumber

actor "Admin" as USER
participant "<<System>>\n SurgicalSync" as SYSTEM

activate USER

    USER -> SYSTEM: wants to list all patient profiles by attributes
    activate SYSTEM
alt Couldn't Find Patient Profile
        
        SYSTEM --> USER :  informs error with suggestion

else Patient Profile Listed Successfully
        SYSTEM --> USER : offers filtering options
    deactivate SYSTEM
        
    USER -> SYSTEM : selects filter or no filter
    activate SYSTEM
       
        SYSTEM --> USER : lists all patient profiles 
    deactivate SYSTEM
end
deactivate USER
@enduml