@startuml
autonumber

actor "Patient" as USER
participant "<<System>>\n SurgicalSync" as SYSTEM

activate USER

    USER -> SYSTEM: wants to create user profile
    activate SYSTEM

        SYSTEM --> USER : requests data (name, email, phoneNumber)
    deactivate SYSTEM
        
    USER -> SYSTEM : provides data
    
    activate SYSTEM
        alt User Already Exists
           USER <-- SYSTEM : informs error with suggestion
        else User Registered Successfully
           USER <-- SYSTEM : shows created user profile
        end
    deactivate SYSTEM
    
deactivate USER
@enduml