@startuml
autonumber

Title "UC26 - Update an operation requisition"

actor "Doctor" as D
participant "<<System>> \n SurgicalSync" as SYSTEM
participant "<<Planning Module>>" as PLANNING

activate D

D -> SYSTEM: asks to update an operation requisition

activate SYSTEM

SYSTEM --> D: asks for the ID of the \n operation request to updated

deactivate SYSTEM

D -> SYSTEM: inserts the operation request ID

alt the logged in doctor is the one who \n created the operation request

activate SYSTEM

SYSTEM --> D: shows the current operation \n request details(priority, deadline)

deactivate SYSTEM

D -> SYSTEM : updates the operation request \n details(priority, deadline)

activate SYSTEM

SYSTEM -> SYSTEM: logs the update \n (change in priority, deadline)

SYSTEM --> D: shows operation success

SYSTEM -> PLANNING : notify of changes to the operation requisition

else The doctor is not authorized to update the request

SYSTEM --> D: shows error message 

deactivate SYSTEM

end

deactivate D

@enduml