@startuml
autonumber

actor "Admin" as USER

participant "FrontEnd" as FE
participant "BackEnd" as BE

activate USER

    USER -> FE: wants to create a patient profile
    activate FE

        FE --> USER : requests data (patientName, birthDate, gender, medicalRecordNumber,\nphoneNumber, medicalConditions, emergencyContact, appointmentHistory, email)
    deactivate FE
        
    USER -> FE : provides data
    activate FE
        alt Email and Phone number are unique
            FE -> BE : POST /Patients
            activate BE
            
                BE --> FE : success: patient profile created 
            deactivate BE
            USER <-- FE : shows created patient profile
            
        else Email and Phone number already exists
            FE -> BE : POST /Patients
            activate BE
            
                BE --> FE : error: email and phone number already exists
            deactivate BE
            USER <-- FE : informs error with suggestion
        end
    deactivate FE
deactivate USER

@enduml