@startuml
autonumber

actor "Admin" as USER

participant "FrontEnd" as FE
participant "BackEnd" as BE

activate USER

    USER -> FE : wants to list operation types
    activate FE
    
        FE -> BE : GET /operationTypes
        activate BE
        
            BE --> FE : returns operation types
        deactivate BE
    
        alt Couldn't Find Operation Types
        FE --> USER : informs error with suggestion
        else Operation Types Listed Successfully
        FE --> USER : offers filtering options
    deactivate FE
    
    USER -> FE : selects filter or no filter
    activate FE
    
        FE -> BE : filters operation types
        activate BE
        
            BE --> FE : returns filtered operation types
        deactivate BE
        
        FE --> USER : lists operation types
        end
        
    deactivate FE
            
deactivate USER

@enduml