@startuml
autonumber

title BackEnd Process View

participant "FrontEnd" as FE
participant "Controllers" as CN
participant "Services" as SV
participant "DTOs" as DTO
participant "Mappers" as MP
participant "Domain" as DM
participant "Firebase IAM API" as IAM
participant "SMTP API" as SMTP
participant "Repositories" as REPO
database "SQL Database" as SQL

activate FE
    FE -> CN: POST /users (with user data)
    activate CN
    
        CN -> SV : Create(UserDTO)
        activate SV
        
            SV -> DTO : Create(UserDTO)
            activate DTO
            
alt User data is valid
            
                DTO --> SV : returns UserDTO
            deactivate DTO
            
            SV -> IAM : create user
            activate IAM
            
                IAM --> SV : returns UID of created user
            deactivate IAM
            
            SV -> IAM : generate password reset link
            activate IAM
            
                IAM --> SV : returns password reset link
            deactivate IAM
            
            SV -> SMTP : send set-up email
            activate SMTP
            
                SMTP --> SV : success: email sent
            deactivate
            
            SV -> MP : MapToDomain(UserDTO)
            activate MP
            
                MP -> DM : Create(User)
                activate DM
                     
                    DM --> MP : returns User
                deactivate DM
            
                MP --> SV : returns User
            deactivate MP
                
            SV -> REPO : AddAsync(User)
            activate REPO
            
                REPO -> SQL : POST /users (User)
                activate SQL
                
                    SQL --> REPO : success: created user (returns user ID)
                deactivate SQL
                
                REPO --> SV : success: created user (returns user ID)
            

            SV --> CN : success: created user (returns user ID) 
        FE <-- CN: success: created user (returns user ID) 

else User data is invalid

                REPO -> SQL : POST /users (User)
                activate SQL
                
                    SQL --> REPO : error: user already exists
                deactivate SQL
                
        REPO --> SV : error: user already exists
            deactivate REPO
            SV --> CN : error: user already exists
        deactivate SV
        FE <-- CN: error: user already exists
    deactivate CN     
               
deactivate FE
end

@enduml