@startuml
autonumber

actor "Admin" as USER

participant "FrontEnd" as FE
participant "BackEnd" as BE

activate USER

    USER -> FE : wants to deactivate a staff 
    activate FE
    
    FE -> BE : GET /staff
    activate BE
    
    note left of SV
      Process documented on use case 21
   end note
    
    BE --> FE : return List<StaffDto>
    deactivate BE
    
    FE --> USER : shows list of staff
    deactivate FE

    USER -> FE : selects a staff to remove 
    activate FE
    
    alt 
    FE -> BE : DEACTIVATE /staff/(id)
    activate BE
    
    BE --> FE : return operation success
    deactivate BE
    
    FE --> USER: operation success

    
    else 
    FE -> BE : DEACTIVATE /staff/(id)
        activate BE
        
        BE --> FE : error:  couldn't find staff
        deactivate BE
        
        FE --> USER: informs error with suggestion
        deactivate FE
        
    end 
    
   
deactivate USER

@enduml