@startuml

skinparam component {
    FontSize 30
    FontName Courier
    BorderColor Black
    BackgroundColor LightGreen
    ArrowFontName Impact
}

component [<<System>>\nHospital] as COMPONENT {
    component "Back End\n Data Management" as BE
    component "Front End" as FE
    component "Planning" as PLANNING
}

FE -up- "     UI"
BE -up- "   API"
BE -right- FE
BE -down- PLANNING

@enduml