@startuml
autonumber

title BackEnd Process View

participant "FrontEnd" as FE
participant "Controllers" as CN
participant "Services" as SV
participant "DTOs" as DTO
participant "Mappers" as MP
participant "Domain" as DM
participant "Repositories" as REPO
database "SQL Database" as SQL

activate FE

    FE -> CN: POST /Patients (with given data)
    activate CN
        
        CN -> SV : Create(PatientDTO)
        activate SV
        
            SV -> REPO : listOfUserData()
            activate REPO 
            
                REPO -> SQL : GET /Users
                activate SQL
                
                    SQL --> REPO: returns listOfUserData
                deactivate SQL
                
                REPO --> SV: returns listOfUserData
            deactivate REPO
        
        SV -> SV : verifyData (email,phoneNumber)
        
    alt Email and Phone number are unique

            SV -> DTO : Create(PatientDTO)
            activate DTO
    
                DTO --> SV : returns PatientDTO
            deactivate DTO
            
            SV -> MP : ToDomain(PatientDTO)
            activate MP
            
                MP -> DM : Create(Patient)
                activate DM
                
                    DM --> MP : returns Patient   
                deactivate DM
                
                MP --> SV : returns Patient
            deactivate MP
            
            SV -> REPO : AddAsync(Patient)
            activate REPO
                    
                REPO -> SQL : POST /Patients
                activate SQL
                    
                    SQL --> REPO : success : created patient profile (returns patient ID)
                deactivate SQL
                    
                REPO --> SV : created patient profile (returns patient ID)
            deactivate REPO
          
            SV --> CN : success: created patient profile (returns patient ID)
            
    FE <-- CN: success: created patient profile(returns patient ID) 

    else Email and Phone number already exists
            
             SV --> CN : error: patient profile already exists
        deactivate SV
        
    FE <-- CN: error: patient already exists
    deactivate CN                
    
end

@enduml