@startuml
autonumber

actor "Admin" as USER
participant "<<System>>\n SurgicalSync" as SYSTEM

activate USER

    USER -> SYSTEM: wants to edit a staff profile
    activate SYSTEM

        SYSTEM --> USER : asks to select a profile and request data
    deactivate SYSTEM
    
    USER -> SYSTEM: select the profile and data
        
        alt valid data 
            USER <-- SYSTEM : success: staff profile edited
        else staff doesn't exist or data is not correct
            USER <-- SYSTEM : error: staff doesn't exist or data is not correct
        end
    deactivate SYSTEM
    
deactivate USER
@enduml