@startuml
autonumber

actor "Admin" as USER

participant "FrontEnd" as FE
participant "BackEnd" as BE

activate USER

    USER -> FE: wants to search for patient profiles
    activate FE
        
        FE --> USER : asks for patient id
    deactivate FE 
       
    USER -> FE: provides patient id
    activate FE
    
         FE -> BE : GET /Patients/id
        activate BE 
        
alt Couldn't Find Patient Profile
            
            BE --> FE : returns error message

    USER <-- FE : informs error with suggestion
            
else Patient Profile Found

            BE --> FE : returns patient
        deactivate BE 
        
            FE --> USER : shows patient profile
end
        
    deactivate FE
    
deactivate USER
@enduml
