@startuml
autonumber

actor "FrontEnd" as FE

participant "BackEnd" as BE
participant "Controllers" as CN
participant "DTOs" as DTO
participant "Services" as SV
participant "Domain" as DM
participant "Repositories" as REPO
database "SQL Database" as SQL

activate FE

    FE -> BE: POST /users-backoffice (with user data)
    activate BE
        
        BE -> CN : Create(UserDTO)
        activate CN
        
            CN -> DTO : Create(UserDTO)
            activate DTO
            
                DTO -> SV : AddAsync(UserDTO)
                activate SV
                    
                    alt User already exists
                        SV --> DTO : error: User already exists
                        DTO --> CN : error: User already exists
                        CN --> BE : error: User already exists
                        BE --> FE : error: User already exists
                    else User does not exist
                        SV -> REPO : AddAsync(User)
                        activate REPO
                        
                            REPO -> SQL : POST /users-backoffice (User)
                            activate SQL
                            
                                SQL --> REPO : success: created user (returns user ID)
                            deactivate SQL
                            
                            REPO --> SV : success: created user (returns user ID)
                        deactivate REPO
                        
                        SV --> DTO : success: created user (returns user ID)
                        DTO --> CN : success: created user (returns user ID)
                    deactivate DTO
                deactivate SV
                
            CN --> BE : success or error: created user (or user already exists)
        deactivate CN

        BE --> FE: success or error: created user (or user already exists)
    deactivate BE
    end
deactivate FE   

@enduml
