@startuml
autonumber

actor "Admin" as USER
participant "<<System>>\n SurgicalSync" as SYSTEM

activate USER

    USER -> SYSTEM: wants to list operation types
    activate SYSTEM

        alt Couldn't Find Operation Types
            USER <-- SYSTEM : informs error with suggestion
        else Operation Type Listed Successfully
            SYSTEM --> USER : offers filtering options
    deactivate SYSTEM
    
    USER -> SYSTEM: selects filter or no filter
    activate SYSTEM
        
            USER <-- SYSTEM : lists all operation types
        end
        
    deactivate SYSTEM
    
deactivate USER
@enduml