@startuml
autonumber

title BackEnd Process View

participant "FrontEnd" as FE
participant "Controllers" as CN
participant "Services" as SV
participant "Domain" as DM


activate FE
        
        FE -> CN : DELETE /staff/id
        activate CN
        
        CN -> SV: DELETE /staff/id
        activate SV
        
        SV -> DM: Deactivate(staff) 
        activate DM
                        
                DM --> SV : returns deactivated staff 
            deactivate DM
            
        SV --> CN : success: deactivated staff 
        deactivate SV
           
       
       CN --> FE : success: deactivated staff 
       deactivate CN   
               
deactivate FE


@enduml