@startuml
autonumber

Title "UC25 - List staff profiles"

participant "FrontEnd" as FE
participant "Controllers" as C
participant "Services" as S
participant "Repositories" as R
participant "Mappers" as M
participant "DTOs" as DTO
database "SQL Database" as SQL

alt Get by id
activate FE
FE -> C : GET /staff?LicenseNumber={id}

activate C

    C -> S : GetByIdAsync(id)
    
    activate S
    
    S -> R : GetByIdAsync(id)
    
    activate R
    
    R -> SQL : SELECT * FROM staff WHERE ID = id
    
    activate SQL
    
    SQL --> R : staff
    
    deactivate SQL 
    
    R --> S : Staff
    
    deactivate R
    
    S -> M : ToDTO(Staff)
    
    activate M
    
    M -> DTO : Create(Staff)
    
    activate DTO
    
    DTO --> M : StaffDto
    
    deactivate DTO 
    
    M --> S : StaffDto
    
    deactivate M
    
    S --> C : StaffDto
    
    deactivate S
    
    C --> FE : StaffDto
    
deactivate C

else get by name

FE -> C : GET /staff?staffName={staffName}

activate C

    C -> S : GetAllByNameAsync(staffName)
    
    activate S
    
    S -> R : GetAllByNameAsync(staffName)
    
    activate R
    
    R -> SQL : SELECT * FROM staff WHERE StaffName = staffName
    
    activate SQL
    
    SQL --> R : list<Staff> staffs
    
    deactivate SQL 
    
    R --> S : list<Staff> staffs
    
    deactivate R
    
    S -> M : ToListDTO(staff)
    
    activate M
    
    loop for all the Staffs on the list
    M -> DTO : Create(Staff)
    
    activate DTO
    
    DTO --> M : StaffDto
    
    deactivate DTO 
    
    
    end
    M --> S : List<StaffDto> StaffsDto
    
    deactivate M
    
    S --> C : List<StaffDto> StaffsDto
    
    deactivate S
    
    C --> FE : List<StaffDto> StaffsDto
    
deactivate C


else  get by specialization
     
     FE -> C : GET /staff?staffSpecialization={staffSpecialization}
     
     activate C
     
         C -> S : GetAllBySpecializationAsync(staffSpecialization)
         
         activate S
         
         S -> R : GetAllBySpecializationAsync(staffSpecialization)
         
         activate R
         
         R -> SQL : SELECT * FROM staff WHERE StaffSpecialization = staffSpecialization
         
         activate SQL
         
         SQL --> R : list<Staff> staffs
         
         deactivate SQL 
         
         R --> S : list<Staff> staffs
         
         deactivate R
         
         S -> M : ToListDTO(staff)
         
         activate M
         
         loop for all the Staffs on the list
         M -> DTO : Create(Staff)
         
         activate DTO
         
         DTO --> M : StaffDto
         
         deactivate DTO 
            end
             M --> S : List<StaffDto> StaffsDto
             
             deactivate M
             
             S --> C : List<StaffDto> StaffsDto
             
             deactivate S
             
             C --> FE : List<StaffDto> StaffsDto
             
         deactivate C
         

        
        
else  get by email
     
     FE -> C : GET /staff?staffEmail={staffEmail}
     
     activate C
     
         C -> S : GetAllByEmailAsync(staffEmail)
         
         activate S
         
         S -> R : GetAllByEmailAsync(staffEmail)
         
         activate R
         
         R -> SQL : SELECT * FROM staff WHERE StaffEmail = staffEmail
         
         activate SQL
         
         SQL --> R :  staff
         
         deactivate SQL 
         
         R --> S : staff
         
         deactivate R
         
         S -> M : ToDto(staff)
         
         activate M
         
       
         M -> DTO : Create(Staff)
         
         activate DTO
         
         DTO --> M : StaffDto
         
         deactivate DTO 
             M --> S : StaffDto
             
             deactivate M
             
             S --> C : StaffDto
             
             deactivate S
             
             C --> FE : StaffDto
             
         deactivate C
         

         
end


deactivate FE 

@enduml