@startuml
autonumber

title "UC34 - Search for an operation requisition"

participant "FrontEnd" as FE
participant "Controllers" as C
participant "Services" as S
participant "Repositories" as R
participant "Mappers" as M
participant "DTOs" as DTO
database "SQL Database" as SQL

activate FE

FE -> C : GET /staff/id

activate C

    C -> S : GetByIdAsync(id)
    
    activate S
    
    S -> R : GetByIdAsync(id)
    
    activate R
    
    R -> SQL : SELECT * FROM operationRequests WHERE ID = id
    
    activate SQL
    
    SQL --> R : required staff profile
    
    deactivate SQL 
    
    R --> S : required staff profile request
    
    deactivate R
    
    S -> M : ToDTO(StaffProfileRequest)
    
    activate M
    
    M -> DTO : Create(StaffProfileRequest)
    
    activate DTO
    
    DTO --> M : StaffProfileDTO
    
    deactivate DTO 
    
    M --> S : StaffProfileDTO
    
    deactivate M
    
    S --> C : StaffProfileDTO
    
    deactivate S
    
    C --> FE : StaffProfileDTO
    
deactivate C

deactivate FE 

@enduml