@startuml
autonumber

Title "UC12 - Access Patient Details After Authentication"

actor "Patient" as P
participant "<<System>> \n SurgicalSync" as SYSTEM

activate P 

P -> SYSTEM: asks to access his details

    activate SYSTEM
    
    alt session valid
        
        SYSTEM --> P: displays the patient information

    else session expired
    
        SYSTEM --> P: session expired, prompts re-authentication
        
    deactivate SYSTEM

    end

deactivate P

@enduml
