@startuml
autonumber

actor "Admin" as USER

participant "FrontEnd" as FE
participant "BackEnd" as BE

activate USER

    USER -> FE : wants to create a staff profile
    activate FE
    
        FE --> USER : requests data ( name, email , phone number, specialization and availability slots)
    deactivate FE

    USER -> FE : provides data
    activate FE
    
            alt Staff Profile Already Exists
               
                
                FE --> USER : informs error with suggestion
            else Staff Profile Created Successfully
            
                FE -> BE : POST /staff (with staff data)
                activate BE
                
                    BE --> FE : success: created staff profile (returns staff ID)
                deactivate BE
                        
        FE --> USER : shows success message
    deactivate FE
    end
            
deactivate USER

@enduml