@startuml
autonumber

actor "Admin" as USER
participant "<<System>>\n SurgicalSync" as SYSTEM

activate USER

   
        
    USER -> SYSTEM : selects a staff 
    activate SYSTEM
    
    SYSTEM --> USER: show staff's details
    
  
deactivate USER
@enduml