@startuml
autonumber

Title "UC28 - Search operation requests"

actor "Doctor" as D
participant "<<System>> \n SurgicalSync" as SYSTEM

activate D

D -> SYSTEM: requests to search for operation requests

    activate SYSTEM
    
    SYSTEM --> D: shows the different filters (id, patientName, \n medicalRecordNumber, operationType and dateRange) \n that can be applied to the search and asks to select one
    
    deactivate SYSTEM
    
    D -> SYSTEM: chooses the filter to be applied

    alt the requested operation request exists 
    
    activate SYSTEM
    
    SYSTEM --> D: shows the operation requests details (eg., patient name, operation type,\n priority, deadlineDate, licenseNumber and medicalRecordNumber)

    else
    
    SYSTEM --> D : shows error message
    
    deactivate SYSTEM
    
    end
    
deactivate D

@enduml