@startuml
autonumber

actor "Admin" as USER

participant "FrontEnd" as FE
participant "BackEnd" as BE

activate USER

    USER -> FE : wants to add a new operation type
    activate FE
    
        FE --> USER : requests data (name, requiredStaff, duration)
    deactivate FE

    USER -> FE : provides data
   
        activate FE
        
            alt User Already Exists
               
            FE -> BE : POST /operationTypes (with given data)
            activate BE
            
                BE --> FE : error: operation type already exists
            deactivate BE 
            FE --> USER : informs error with suggestion
            
            else User Created Successfully
            
            FE -> BE : POST /operationTypes (with given data)
            activate BE
            
                BE --> FE : success: returns success message
            deactivate BE
               
            FE --> USER : shows success message
        deactivate FE
    end
            
deactivate USER

@enduml