@startuml
autonumber

actor "Backoffice User" as USER
participant "<<System>>\n SurgicalSync" as SYSTEM
participant "SMTP API" as EMAIL
participant "Firebase IAM API" as FIREBASE

activate USER

    USER -> SYSTEM: wants to reset my password
    activate SYSTEM

        SYSTEM --> USER : requests email
    deactivate SYSTEM
        
    USER -> SYSTEM : provides email
    
    activate SYSTEM
        alt User Doesn't Exist
           USER <-- SYSTEM : informs error with suggestion
        else User Exists
            
         SYSTEM -> EMAIL : sends email to setup password
            activate EMAIL
                EMAIL --> SYSTEM : email sent
            deactivate EMAIL
    
    SYSTEM --> USER: email with link to reset sent
    deactivate SYSTEM
    
    USER -> SYSTEM: provides new password
    activate SYSTEM
    
    alt password meets system’s password complexity rules
    
          SYSTEM -> FIREBASE : update password
                   activate FIREBASE
                   
         
          FIREBASE--> SYSTEM: shows success
          deactivate FIREBASE
          
          SYSTEM --> USER: shows operation success
          
    else  password not meets system’s password complexity rules
    
    SYSTEM --> USER: shows error: password not meets system’s\n password complexity rules
    deactivate SYSTEM          
                  
                  
    end 
    end              
    deactivate SYSTEM
    
deactivate USER
@enduml