name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0

      - name: Build .NET project
        run: |
          dotnet build

      - name: Run tests
        run: |
          dotnet test
          
      - name: Publish .NET project
        run: |
          dotnet publish -c Release -o ./publish
          
      - name: Transfer files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: ./publish/*
          target: /${{ secrets.SSH_USERNAME }}/production

      - name: Setup SSH
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-add ~/.ssh/deploy_key
          nslookup ${{ secrets.SSH_HOST }} || (echo "Hostname resolution failed!" && exit 1)
          ssh-keyscan -p 10761 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    
      - name: Deploy backend code
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          WORK_DIR: ${{ secrets.WORK_DIR }}
        run: |
          # Copy backend files to the server
          scp -P 10761 -i ~/.ssh/deploy_key -r ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/apps/backend/

          # Connect to the server and execute the build script
          ssh -p 10761 -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /root/apps/backend/
            chmod +x ./buildBackend.sh
            ./buildBackend.sh
          EOF
