name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          nslookup ${{ secrets.SSH_HOST }} || (echo "Hostname resolution failed!" && exit 1)
          ssh-keyscan -p 10761 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy backend code
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          WORK_DIR: ${{ secrets.WORK_DIR }}
        run: |
          # Copy backend files to the server
          scp -P 10761 -i ~/.ssh/deploy_key -r ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/apps/backend/

          # Connect to the server and execute the build script
          ssh -p 10761 -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /root/apps/backend/
            chmod +x ./buildBackend.sh
            ./buildBackend.sh
          EOF
