@startuml
autonumber

title BackEnd Process View

participant "FrontEnd" as FE
participant "Controllers" as CN
participant "Services" as SV
participant "Domain" as DM
participant "Repositories" as REPO
database "SQL Database" as SQL

activate FE

    FE -> CN: GET /Patients
    activate CN
    
        CN -> SV : GetAllAsync()
        activate SV
        
            note left of SV
                Process documented on use case 16
            end note
            
            SV --> CN : returns List<PatientDTO>
        deactivate SV
        
        CN --> FE : returns List<PatientDTO>
    deactivate CN
    
    FE -> CN : DELETE /Patients/id
    activate CN
        
        CN -> SV : Delete(id)
        activate SV
alt Patient Deleted Successfully
            SV -> DM : Delete(Patient)
            activate DM
            
                DM --> SV : returns updated Patient
            deactivate DM
            
            SV -> REPO : InactivateAsync(Patient)
            activate REPO
            
                REPO -> SQL : INACTIVATE /Patients/id
                activate SQL
                
                    SQL --> REPO : success: patient profile deleted
                deactivate SQL
                
                REPO --> SV : success: patient profile deleted
            deactivate REPO
            
            SV --> CN : success: patient profile deleted           
        CN --> FE : success: patient profile deleted
    
else Couldn't Find Patient Profile
            
            SV --> CN : error : couldn't find patient profile
        deactivate SV
        
        CN --> FE : error : couldn't find patient profile
    deactivate CN
end                
deactivate FE
@enduml