@startuml
autonumber

title BackEnd Process View

participant "FrontEnd" as FE
participant "Controllers" as CN
participant "Services" as SV
participant "DTOs" as DTO
participant "Mappers" as MP
participant "Domain" as DM
participant "Repositories" as REPO
database "SQL Database" as SQL

activate FE
    FE -> CN: POST /staff (with given data)
    activate CN
    
        CN -> SV : Create(StaffProfileDTO)
        activate SV
        
            SV -> DTO : Create(StaffProfileDTO)
            activate DTO
            
alt Staff Profile data is valid
            
                DTO --> SV : returns StaffProfileDTO
            deactivate DTO
            
            SV -> MP : MapToDomain(StaffProfileDTO)
            activate MP
            
                MP -> DM : Create(StaffProfile)
                activate DM
                     
                    DM --> MP : returns StaffProfile
                deactivate DM
            
                MP --> SV : returns StaffProfile
            deactivate MP
                
            SV -> REPO : AddAsync(StaffProfile)
            activate REPO
            
                REPO -> SQL : POST /staff (StaffProfile)
                activate SQL
                
                    SQL --> REPO : success: created staff profile (returns ID)
                deactivate SQL
                
                REPO --> SV : success: added staff profile (returns ID)
            

            SV --> CN : success: added staff profile (returns ID)
        FE <-- CN: success: added staff profile (returns ID) 

else Staff Profile(email and/or phone number) already exists

                REPO -> SQL : POST /staff (StaffProfile)
                activate SQL
                
                    SQL --> REPO : error: staff profile(email and/or phone number) already exists
                deactivate SQL
                
        REPO --> SV : error: staff profile already exists
            deactivate REPO
            SV --> CN : error: staff profile already exists
        deactivate SV
        FE <-- CN: error: staff profile already exists
    deactivate CN     
               
deactivate FE
end

@enduml